---
title: "9185_project1"
author: "Shubo Zhang"
date: "2024-02-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(ggplot2)
library(reshape2)

virals <- read.csv("baseline.csv")
endpoints <- read.csv("endpoints.csv")
```

```{r}
### viral loads in the blood plasma
#### A effect
virals_blood_long = melt(virals, id.var = c("ptid", "period1", "period2", "period3"), measure.vars = c("bviral0", "bviral1", "bviral2", "bviral3", "bviral4", "bviral5", "bviral6"))

A_pureeffect <- virals_blood_long[virals_blood_long$period1=="Pill A"&virals_blood_long$variable %in% c("bviral0", "bviral1", "bviral2"),]
A_pureeffect$group = "A"
A_pureeffect <- A_pureeffect[, -c(2,3,4)]
A_pureeffect$variable <- ifelse(A_pureeffect$variable=="bviral0", "Before", ifelse(A_pureeffect$variable=="bviral1", "After", "Washout"))

BAC_effect <- virals_blood_long[(virals_blood_long$period1=="Gel B"&virals_blood_long$period2=="Pill A"&virals_blood_long$variable %in% c("bviral2", "bviral3", "bviral4")),]
BAC_effect$group = "BA"
BAC_effect <- BAC_effect[,-c(2,3,4)]
BAC_effect$variable <- ifelse(BAC_effect$variable=="bviral2", "Before", ifelse(BAC_effect$variable=="bviral3", "After", "Washout"))

CBA_effect <- virals_blood_long[(virals_blood_long$period2=="Gel B"&virals_blood_long$period3=="Pill A"&virals_blood_long$variable %in% c("bviral4", "bviral5", "bviral6")),]
CBA_effect$group = "BA"
CBA_effect <- CBA_effect[,-c(2,3,4)]
CBA_effect$variable <- ifelse(CBA_effect$variable=="bviral4", "Before", ifelse(CBA_effect$variable=="bviral5", "After", "Washout"))

CAB_effect <- virals_blood_long[(virals_blood_long$period1=="Gel C"&virals_blood_long$period2=="Pill A"&virals_blood_long$variable %in% c("bviral2", "bviral3", "bviral4")),]
CAB_effect$group = "CA"
CAB_effect <- CAB_effect[,-c(2,3,4)]
CAB_effect$variable <- ifelse((CAB_effect$variable=="bviral2"), "Before", ifelse(CAB_effect$variable=="bviral3", "After", "Washout"))

BCA_effect <- virals_blood_long[(virals_blood_long$period2=="Gel C"&virals_blood_long$period3=="Pill A"&virals_blood_long$variable %in% c("bviral4", "bviral5", "bviral6")),]
BCA_effect$group = "CA"
BCA_effect <- BCA_effect[,-c(2,3,4)]
BCA_effect$variable <- ifelse((BCA_effect$variable=="bviral4"), "Before", ifelse(BCA_effect$variable=="bviral5", "After", "Washout"))

Aeffect <- rbind(A_pureeffect,BAC_effect,CBA_effect, BCA_effect, CAB_effect)
#### B effect
B_pureeffect <- virals_blood_long[virals_blood_long$period1=="Gel B"&virals_blood_long$variable %in% c("bviral0", "bviral1", "bviral2"),]
B_pureeffect$group = "B"
B_pureeffect <- B_pureeffect[, -c(2,3,4)]
B_pureeffect$variable <- ifelse(B_pureeffect$variable=="bviral0", "Before", ifelse(B_pureeffect$variable=="bviral1", "After", "Washout"))

ABC_effect <- virals_blood_long[(virals_blood_long$period1=="Pill A"&virals_blood_long$period2=="Gel B"&virals_blood_long$variable %in% c("bviral2", "bviral3", "bviral4")),]
ABC_effect$group = "AB"
ABC_effect <- ABC_effect[,-c(2,3,4)]
ABC_effect$variable <- ifelse(ABC_effect$variable=="bviral2", "Before", ifelse(ABC_effect$variable=="bviral3", "After", "Washout"))

CAB_effect <- virals_blood_long[(virals_blood_long$period2=="Pill A"&virals_blood_long$period3=="Gel B"&virals_blood_long$variable %in% c("bviral4", "bviral5", "bviral6")),]
CAB_effect$group = "AB"
CAB_effect <- CAB_effect[,-c(2,3,4)]
CAB_effect$variable <- ifelse(CAB_effect$variable=="bviral4", "Before", ifelse(CAB_effect$variable=="bviral5", "After", "Washout"))

CBA_effect <- virals_blood_long[(virals_blood_long$period1=="Gel C"&virals_blood_long$period2=="Gel B"&virals_blood_long$variable %in% c("bviral2", "bviral3", "bviral4")),]
CBA_effect$group = "CB"
CBA_effect <- CBA_effect[,-c(2,3,4)]
CBA_effect$variable <- ifelse((CBA_effect$variable=="bviral2"), "Before", ifelse(CBA_effect$variable=="bviral3", "After", "Washout"))

ACB_effect <- virals_blood_long[(virals_blood_long$period2=="Gel C"&virals_blood_long$period3=="Gel B"&virals_blood_long$variable %in% c("bviral4", "bviral5", "bviral6")),]
ACB_effect$group = "CB"
ACB_effect <- ACB_effect[,-c(2,3,4)]
ACB_effect$variable <- ifelse((ACB_effect$variable=="bviral4"), "Before", ifelse(ACB_effect$variable=="bviral5", "After", "Washout"))

Beffect <- rbind(B_pureeffect,ABC_effect,CAB_effect, CBA_effect, ACB_effect)

#### C effect
C_pureeffect <- virals_blood_long[virals_blood_long$period1=="Gel C"&virals_blood_long$variable %in% c("bviral0", "bviral1", "bviral2"),]
C_pureeffect$group = "C"
C_pureeffect <- C_pureeffect[, -c(2,3,4)]
C_pureeffect$variable <- ifelse(C_pureeffect$variable=="bviral0", "Before", ifelse(C_pureeffect$variable=="bviral1", "After", "Washout"))

ACB_effect <- virals_blood_long[(virals_blood_long$period1=="Pill A"&virals_blood_long$period2=="Gel C"&virals_blood_long$variable %in% c("bviral2", "bviral3", "bviral4")),]
ACB_effect$group = "AC"
ACB_effect <- ACB_effect[,-c(2,3,4)]
ACB_effect$variable <- ifelse(ACB_effect$variable=="bviral2", "Before", ifelse(ACB_effect$variable=="bviral3", "After", "Washout"))

BAC_effect <- virals_blood_long[(virals_blood_long$period2=="Pill A"&virals_blood_long$period3=="Gel C"&virals_blood_long$variable %in% c("bviral4", "bviral5", "bviral6")),]
BAC_effect$group = "AC"
BAC_effect <- BAC_effect[,-c(2,3,4)]
BAC_effect$variable <- ifelse(BAC_effect$variable=="bviral4", "Before", ifelse(BAC_effect$variable=="bviral5", "After", "Washout"))

BCA_effect <- virals_blood_long[(virals_blood_long$period1=="Gel B"&virals_blood_long$period2=="Gel C"&virals_blood_long$variable %in% c("bviral2", "bviral3", "bviral4")),]
BCA_effect$group = "BC"
BCA_effect <- BCA_effect[,-c(2,3,4)]
BCA_effect$variable <- ifelse((BCA_effect$variable=="bviral2"), "Before", ifelse(BCA_effect$variable=="bviral3", "After", "Washout"))

ABC_effect <- virals_blood_long[(virals_blood_long$period2=="Gel B"&virals_blood_long$period3=="Gel C"&virals_blood_long$variable %in% c("bviral4", "bviral5", "bviral6")),]
ABC_effect$group = "BC"
ABC_effect <- ABC_effect[,-c(2,3,4)]
ABC_effect$variable <- ifelse((ABC_effect$variable=="bviral4"), "Before", ifelse(ABC_effect$variable=="bviral5", "After", "Washout"))

Ceffect <- rbind(C_pureeffect,ACB_effect,BAC_effect, BCA_effect, ABC_effect)
```

```{r}
#### A
mean_table = tapply(Aeffect$value, 
                    list(Aeffect$group, Aeffect$variable), 
                    mean, 
                    na.rm = T)
mean_table <- mean_table[,c(2,1,3)]
bviral_mean <- mean_table

mycol = c("blue3", "cyan4", "gold3")
par(mfrow=c(1,3))

plot(1:3, c(0,65,130),
     ylab = "Mean of grip-strength", xlab = "", 
     pch = " ", cex.lab = 1, cex.axis = 1 ,
     mgp = c(2.5, 1, 0), axes=FALSE, main = "Pill A")

axis(side=1, 1:3, c("Before","After", "Washout"))
axis(side=2, at=seq(0,130, by=10))
box()
for (i in 1:3) {
  lines(1:3, mean_table[i, ], lty = 2, col = mycol[i], lwd = 3)
}
legend(2, 130, legend = c("A", "B+A", "C+A"), bty = "n", 
       col = mycol, lwd = 2, ncol = 1, cex = 1)

#### B
mean_table = tapply(Beffect$value, 
                    list(Beffect$group, Beffect$variable), 
                    mean, 
                    na.rm = T)
mean_table <- mean_table[,c(2,1,3)]
mean_table <- mean_table[c(2,1,3),]
bviral_mean <- rbind(bviral_mean, mean_table)

plot(1:3, c(0,65,130),
     ylab = "Mean of grip-strength", xlab = "", 
     pch = " ", cex.lab = 1, cex.axis = 1 ,
     mgp = c(2.5, 1, 0), axes=FALSE, main = "Gel B")
axis(side=1, 1:3, c("Before","After", "Washout"))
axis(side=2, at=seq(0,130, by=10))
box()
for (i in 1:3) {
  lines(1:3, mean_table[i, ], lty = 2, col = mycol[i], lwd = 3)
}
legend(2, 130, legend = c("B", "A+B", "C+B"), bty = "n", 
       col = mycol, lwd = 2, ncol = 1, cex = 1)

#### C
mean_table = tapply(Ceffect$value, 
                    list(Ceffect$group, Ceffect$variable), 
                    mean, 
                    na.rm = T)
mean_table <- mean_table[,c(2,1,3)]
mean_table <- mean_table[c(3,1,2),]
bviral_mean <- rbind(bviral_mean, mean_table)

plot(1:3, c(0,65,130),
     ylab = "Mean of grip-strength", xlab = "", 
     pch = " ", cex.lab = 1, cex.axis = 1 ,
     mgp = c(2.5, 1, 0), axes=FALSE, main = "Gel C")
axis(side=1, 1:3, c("Before","After", "Washout"))
axis(side=2, at=seq(0,130, by=10))
box()
for (i in 1:3) {
  lines(1:3, mean_table[i, ], lty = 2, col = mycol[i], lwd = 3)
}
legend(2, 130, legend = c("C", "A+C", "B+C"), bty = "n", 
       col = mycol, lwd = 2, ncol = 1, cex = 1)
mtext("Longitudinal means of blood virals", side = 3, line = -1.3, outer = TRUE)

kableExtra::kable(bviral_mean)

```

```{r}
### viral loads in the affected skin
#### A effect
virals_skin_long = melt(virals, id.var = c("ptid", "period1", "period2", "period3"), measure.vars = c("sviral0", "sviral1", "sviral2", "sviral3", "sviral4", "sviral5", "sviral6"))

A_pureeffect <- virals_skin_long[virals_skin_long$period1=="Pill A"&virals_skin_long$variable %in% c("sviral0", "sviral1", "sviral2"),]
A_pureeffect$group = "A"
A_pureeffect <- A_pureeffect[, -c(2,3,4)]
A_pureeffect$variable <- ifelse(A_pureeffect$variable=="sviral0", "Before", ifelse(A_pureeffect$variable=="sviral1", "After", "Washout"))

BAC_effect <- virals_skin_long[(virals_skin_long$period1=="Gel B"&virals_skin_long$period2=="Pill A"&virals_skin_long$variable %in% c("sviral2", "sviral3", "sviral4")),]
BAC_effect$group = "BA"
BAC_effect <- BAC_effect[,-c(2,3,4)]
BAC_effect$variable <- ifelse(BAC_effect$variable=="sviral2", "Before", ifelse(BAC_effect$variable=="sviral3", "After", "Washout"))

CBA_effect <- virals_skin_long[(virals_skin_long$period2=="Gel B"&virals_skin_long$period3=="Pill A"&virals_skin_long$variable %in% c("sviral4", "sviral5", "sviral6")),]
CBA_effect$group = "BA"
CBA_effect <- CBA_effect[,-c(2,3,4)]
CBA_effect$variable <- ifelse(CBA_effect$variable=="sviral4", "Before", ifelse(CBA_effect$variable=="sviral5", "After", "Washout"))

CAB_effect <- virals_skin_long[(virals_skin_long$period1=="Gel C"&virals_skin_long$period2=="Pill A"&virals_skin_long$variable %in% c("sviral2", "sviral3", "sviral4")),]
CAB_effect$group = "CA"
CAB_effect <- CAB_effect[,-c(2,3,4)]
CAB_effect$variable <- ifelse((CAB_effect$variable=="sviral2"), "Before", ifelse(CAB_effect$variable=="sviral3", "After", "Washout"))

BCA_effect <- virals_skin_long[(virals_skin_long$period2=="Gel C"&virals_skin_long$period3=="Pill A"&virals_skin_long$variable %in% c("sviral4", "sviral5", "sviral6")),]
BCA_effect$group = "CA"
BCA_effect <- BCA_effect[,-c(2,3,4)]
BCA_effect$variable <- ifelse((BCA_effect$variable=="sviral4"), "Before", ifelse(BCA_effect$variable=="sviral5", "After", "Washout"))

Aeffect <- rbind(A_pureeffect,BAC_effect,CBA_effect, BCA_effect, CAB_effect)
#### B effect
B_pureeffect <- virals_skin_long[virals_skin_long$period1=="Gel B"&virals_skin_long$variable %in% c("sviral0", "sviral1", "sviral2"),]
B_pureeffect$group = "B"
B_pureeffect <- B_pureeffect[, -c(2,3,4)]
B_pureeffect$variable <- ifelse(B_pureeffect$variable=="sviral0", "Before", ifelse(B_pureeffect$variable=="sviral1", "After", "Washout"))

ABC_effect <- virals_skin_long[(virals_skin_long$period1=="Pill A"&virals_skin_long$period2=="Gel B"&virals_skin_long$variable %in% c("sviral2", "sviral3", "sviral4")),]
ABC_effect$group = "AB"
ABC_effect <- ABC_effect[,-c(2,3,4)]
ABC_effect$variable <- ifelse(ABC_effect$variable=="sviral2", "Before", ifelse(ABC_effect$variable=="sviral3", "After", "Washout"))

CAB_effect <- virals_skin_long[(virals_skin_long$period2=="Pill A"&virals_skin_long$period3=="Gel B"&virals_skin_long$variable %in% c("sviral4", "sviral5", "sviral6")),]
CAB_effect$group = "AB"
CAB_effect <- CAB_effect[,-c(2,3,4)]
CAB_effect$variable <- ifelse(CAB_effect$variable=="sviral4", "Before", ifelse(CAB_effect$variable=="sviral5", "After", "Washout"))

CBA_effect <- virals_skin_long[(virals_skin_long$period1=="Gel C"&virals_skin_long$period2=="Gel B"&virals_skin_long$variable %in% c("sviral2", "sviral3", "sviral4")),]
CBA_effect$group = "CB"
CBA_effect <- CBA_effect[,-c(2,3,4)]
CBA_effect$variable <- ifelse((CBA_effect$variable=="sviral2"), "Before", ifelse(CBA_effect$variable=="sviral3", "After", "Washout"))

ACB_effect <- virals_skin_long[(virals_skin_long$period2=="Gel C"&virals_skin_long$period3=="Gel B"&virals_skin_long$variable %in% c("sviral4", "sviral5", "sviral6")),]
ACB_effect$group = "CB"
ACB_effect <- ACB_effect[,-c(2,3,4)]
ACB_effect$variable <- ifelse((ACB_effect$variable=="sviral4"), "Before", ifelse(ACB_effect$variable=="sviral5", "After", "Washout"))

Beffect <- rbind(B_pureeffect,ABC_effect,CAB_effect, CBA_effect, ACB_effect)

#### C effect
C_pureeffect <- virals_skin_long[virals_skin_long$period1=="Gel C"&virals_skin_long$variable %in% c("sviral0", "sviral1", "sviral2"),]
C_pureeffect$group = "C"
C_pureeffect <- C_pureeffect[, -c(2,3,4)]
C_pureeffect$variable <- ifelse(C_pureeffect$variable=="sviral0", "Before", ifelse(C_pureeffect$variable=="sviral1", "After", "Washout"))

ACB_effect <- virals_skin_long[(virals_skin_long$period1=="Pill A"&virals_skin_long$period2=="Gel C"&virals_skin_long$variable %in% c("sviral2", "sviral3", "sviral4")),]
ACB_effect$group = "AC"
ACB_effect <- ACB_effect[,-c(2,3,4)]
ACB_effect$variable <- ifelse(ACB_effect$variable=="sviral2", "Before", ifelse(ACB_effect$variable=="sviral3", "After", "Washout"))

BAC_effect <- virals_skin_long[(virals_skin_long$period2=="Pill A"&virals_skin_long$period3=="Gel C"&virals_skin_long$variable %in% c("sviral4", "sviral5", "sviral6")),]
BAC_effect$group = "AC"
BAC_effect <- BAC_effect[,-c(2,3,4)]
BAC_effect$variable <- ifelse(BAC_effect$variable=="sviral4", "Before", ifelse(BAC_effect$variable=="sviral5", "After", "Washout"))

BCA_effect <- virals_skin_long[(virals_skin_long$period1=="Gel B"&virals_skin_long$period2=="Gel C"&virals_skin_long$variable %in% c("sviral2", "sviral3", "sviral4")),]
BCA_effect$group = "BC"
BCA_effect <- BCA_effect[,-c(2,3,4)]
BCA_effect$variable <- ifelse((BCA_effect$variable=="sviral2"), "Before", ifelse(BCA_effect$variable=="sviral3", "After", "Washout"))

ABC_effect <- virals_skin_long[(virals_skin_long$period2=="Gel B"&virals_skin_long$period3=="Gel C"&virals_skin_long$variable %in% c("sviral4", "sviral5", "sviral6")),]
ABC_effect$group = "BC"
ABC_effect <- ABC_effect[,-c(2,3,4)]
ABC_effect$variable <- ifelse((ABC_effect$variable=="sviral4"), "Before", ifelse(ABC_effect$variable=="sviral5", "After", "Washout"))

Ceffect <- rbind(C_pureeffect,ACB_effect,BAC_effect, BCA_effect, ABC_effect)
```

```{r}
#### A
mean_table = tapply(Aeffect$value, 
                    list(Aeffect$group, Aeffect$variable), 
                    mean, 
                    na.rm = T)
mean_table <- mean_table[,c(2,1,3)]
sviral_mean <- mean_table

mycol = c("blue3", "cyan4", "gold3")
par(mfrow=c(1,3))
plot(1:3, c(0,120,240),
     ylab = "Mean of grip-strength", xlab = "", 
     pch = " ", cex.lab = 1, cex.axis = 1 ,
     mgp = c(2.5, 1, 0), axes=FALSE, main = "Pill A")
axis(side=1, 1:3, c("Before","After", "Washout"))
axis(side=2, at=seq(0,240, by=20))
box()
for (i in 1:3) {
  lines(1:3, mean_table[i, ], lty = 2, col = mycol[i], lwd = 3)
}
legend(2, 240, legend = c("A", "B+A", "C+A"), bty = "n", 
       col = mycol, lwd = 2, ncol = 1, cex = 1)

#### B
mean_table = tapply(Beffect$value, 
                    list(Beffect$group, Beffect$variable), 
                    mean, 
                    na.rm = T)
mean_table <- mean_table[,c(2,1,3)]
mean_table <- mean_table[c(2,1,3),]
sviral_mean <- rbind(sviral_mean, mean_table)


plot(1:3, c(0,120,240),
     ylab = "Mean of grip-strength", xlab = "", 
     pch = " ", cex.lab = 1, cex.axis = 1 ,
     mgp = c(2.5, 1, 0), axes=FALSE, main = "Gel B")
axis(side=1, 1:3, c("Before","After", "Washout"))
axis(side=2, at=seq(0,240, by=20))
box()
for (i in 1:3) {
  lines(1:3, mean_table[i, ], lty = 2, col = mycol[i], lwd = 3)
}
legend(2, 240, legend = c("B", "A+B", "C+B"), bty = "n", 
       col = mycol, lwd = 2, ncol = 1, cex = 1)

#### C
mean_table = tapply(Ceffect$value, 
                    list(Ceffect$group, Ceffect$variable), 
                    mean, 
                    na.rm = T)
mean_table <- mean_table[,c(2,1,3)]
mean_table <- mean_table[c(3,1,2),]
sviral_mean <- rbind(sviral_mean, mean_table)

plot(1:3, c(0,120,240),
     ylab = "Mean of grip-strength", xlab = "", 
     pch = " ", cex.lab = 1, cex.axis = 1 ,
     mgp = c(2.5, 1, 0), axes=FALSE, main = "Gel C")
axis(side=1, 1:3, c("Before","After", "Washout"))
axis(side=2, at=seq(0,240, by=20))
box()
for (i in 1:3) {
  lines(1:3, mean_table[i, ], lty = 2, col = mycol[i], lwd = 3)
}
legend(2, 240, legend = c("C", "A+C", "B+C"), bty = "n", 
       col = mycol, lwd = 2, ncol = 1, cex = 1)
mtext("Longitudinal means of skin virals", side = 3, line = -1.3, outer = TRUE)

kableExtra::kable(sviral_mean)

```

```{r}
### adverse event EDA
adverse <- endpoints[,c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16)]
adverse$period1_count <- adverse$AE_pillA_week1+adverse$AE_pillA_week2+adverse$AE_pillA_week3+adverse$AE_pillA_week4
adverse$period2_count <- adverse$AE_gelB_week1+adverse$AE_gelB_week2+adverse$AE_gelB_week3+adverse$AE_gelB_week4
adverse$period3_count <- adverse$AE_gelC_week1+adverse$AE_gelC_week2+adverse$AE_gelC_week3+adverse$AE_gelC_week4
adverse<-adverse[,-c(5,6,7,8,9,10,11,12,13,14,15,16)]

adverse_long = melt(adverse, id.var = c("ptid", "period1", "period2", "period3"), measure.vars = c("period1_count", "period2_count", "period3_count"))

adverse$A_count=adverse$B_count=adverse$C_count=0
for (i in 1:180){
  if (adverse$period1[i]=="Pill A") adverse$A_count[i]=adverse$period1_count[i]
  if (adverse$period2[i]=="Pill A") adverse$A_count[i]=adverse$period2_count[i]
  if (adverse$period3[i]=="Pill A") adverse$A_count[i]=adverse$period3_count[i]
  
  if (adverse$period1[i]=="Gel B") adverse$B_count[i]=adverse$period1_count[i]
  if (adverse$period2[i]=="Gel B") adverse$B_count[i]=adverse$period2_count[i]
  if (adverse$period3[i]=="Gel B") adverse$B_count[i]=adverse$period3_count[i]
  
  if (adverse$period1[i]=="Gel C") adverse$C_count[i]=adverse$period1_count[i]
  if (adverse$period2[i]=="Gel C") adverse$C_count[i]=adverse$period2_count[i]
  if (adverse$period3[i]=="Gel C") adverse$C_count[i]=adverse$period3_count[i]
}
countdata <- adverse[,c(10,9,8)]

A=as.data.frame(countdata[,1])
colnames(A)<-"count"
B=as.data.frame(countdata[,2])
colnames(B)<-"count"
C=as.data.frame(countdata[,3])
colnames(C)<-"count"
newdata <- rbind(A,B,C)
newdata$group = 0
for (i in 1:540){
  if (i<=180) newdata$group[i]="Pill A"
  else if (i<=360) newdata$group[i]="Gel B"
  else newdata$group[i]="Gel C"
}
library(ggplot2)
hist(newdata)
# Histogram by group in ggplot2
ggplot(newdata, aes(x = count, fill = group)) + 
  geom_histogram(binwidth = 0.5, color = "black", alpha = 0.7)+
  labs(x = "Factor Levels", y = "Frequency", title = "Histogram of adverse event total count")
```

```{r}
### adherence days
adhere <- endpoints[,c(1,2,3,4,17,18,19,20,21,22,23,24,25,26,27,28)]
adhere.melt <- melt(adhere, id.vars = c("ptid", "period1", "period2", "period3"))

temp=data.frame(rep(0,2160))
colnames(temp)<-"group"
temp$count=NA
for (i in 1:180){
  temp$group[c(12*i-11,12*i-10,12*i-9,12*i-8)]=adhere$period1[i]
  temp$count[c(12*i-11,12*i-10,12*i-9,12*i-8)]=as.vector(adhere[i,5:8])
  
  temp$group[c(12*i-7,12*i-6,12*i-5,12*i-4)]=adhere$period2[i]
  temp$count[c(12*i-7,12*i-6,12*i-5,12*i-4)]=as.vector(adhere[i,9:12])
  
  temp$group[c(12*i-3,12*i-2,12*i-1,12*i)]=adhere$period3[i]
  temp$count[c(12*i-3,12*i-2,12*i-1,12*i)]=as.vector(adhere[i,13:16])
}
temp$count <- as.numeric(temp$count)
hist(temp$count[temp$group=="Pill A"])
ggplot(temp, aes(x = count, fill=group)) + 
  geom_histogram(binwidth = 0.5, color = "black", alpha = 0.7)+
  labs(x = "Adherence days per week", y = "Frequency", title = "Histogram of adherence count")
```

